services:
  mediscan_db:
    image: postgres:17
    container_name: mediscan-db
    volumes:
      - mediscan_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=mediscandb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    networks:
      - mediscan-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "mediscandb", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: mediscan-backend
    ports:
      - 8000:8000
    depends_on:
      mediscan_db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    networks:
      - mediscan-network
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: mediscan-frontend
    ports:
      - 5173:5173
    networks:
      - mediscan-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    networks:
      - mediscan-network
    volumes:
      - ollama_data:/root/.ollama
    entrypoint:
      /bin/bash -c "ollama serve & sleep 5 && ollama pull llama3.2:3b && tail -f /dev/null"

  ocr_service:
    build: ./ocrService/easyOCR
    container_name: ocr-service
    ports:
      - 5000:5000
    networks:
      - mediscan-network
    volumes:
      - ocr_service_data:/root/.ocr_service_data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes", "--bind", "0.0.0.0"]
    networks:
      - mediscan-network

  reminder_service:
    build: ./reminderService
    container_name: reminder-service
    depends_on:
      - redis
      - backend
    ports:
      - '9002:9002'
    networks:
      - mediscan-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/root/.minio_data
    networks:
      - mediscan-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


networks:
  mediscan-network:

volumes:
  mediscan_data:
  ollama_data:
  ocr_service_data:
  minio_data:
